# Auto-generated by discover_files.py -- REVIEW BEFORE USE
# Import this into run_pipeline.py: 
#   from discovered_subject_file_map import SUBJECT_FILE_MAP

SUBJECT_FILE_MAP = {
    'B01': {
        'machine': 'natus',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B01_00/B01_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B01_01T/B01_01TR1.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B01_01T/B01_01TR2.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B01_01T/B01_01TR3.edf'],
    },
    'B02': {
        'machine': 'natus',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B02_00/B02_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B02_01T/B02_01TR1.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B02_01T/B02_01TR2.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B02_01T/B02_01TR3.edf'],
    },
    'B04': {
        'machine': 'natus',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B04_00/B04_00R1.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B04_00/B04_00R2.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B04_00/B04_00R3.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B04_01T/B04_01TR2.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B04_01T/B04_01TR3.edf'],
    },
    'B17': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B17_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B17_01T.edf'],
    },
    'B22': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B22_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B22_01T.edf'],
    },
    'B26': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B26_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B26_01T.edf'],
    },
    'B27': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B27_00/B27_00R1.edf', '/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B27_00/B27_00R2R3.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B27_01T.edf'],
    },
    'B28': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B28_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B28_01T.edf'],
    },
    'B29': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B29_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B29_01T.edf'],
    },
    'B31': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B31_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B31_01T.edf'],
    },
    'B32': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B32_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B32_01T.edf'],
    },
    'B33': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B33_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B33_01T.edf'],
    },
    'B34': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B34_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B34_01T.edf'],
    },
    'B35': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B35_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B35_01T.edf'],
    },
    'B36': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B36_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B36_01T.edf'],
    },
    'B37': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B37_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B37_01T.edf'],
    },
    'B41': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B41_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B41_01T.edf'],
    },
    'B42': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B42_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B42_01T.edf'],
    },
    'B43': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B43_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B43_01T.edf'],
    },
    'B44': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B44_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B44_01T.edf'],
    },
    'B45': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B45_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B45_01T.edf'],
    },
    'B47': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B47_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B47_01T.edf'],
    },
    'B51': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B51_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B51_01T.edf'],
    },
    'B54': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B54_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B54_01T.edf'],
    },
    'B55': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B55_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B55_01T.edf'],
    },
    'B56': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B56_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B56_01T.edf'],
    },
    'B57': {
        'machine': 'neurosoft',
        'pre_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B57_00.edf'],
        'post_files': ['/mnt/data_lab513/thupnm/BrainTrain-prepost-group/EEG/raweeg_01m/B57_01T.edf'],
    },
}
